version: "3"
services:
  notebook:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./mywork:/home/jovyan/mywork
      - ~/.ssh:/home/jovyan/.ssh
      - ~/.gitconfig:/home/jovyan/.gitconfig
      - ~/.kaggle:/home/jovyan/.kaggle
    command: 
      jupyter lab --ip=0.0.0.0 --no-browser --port=8888 --NotebookApp.token='' --notebook-dir=/home/jovyan
